feat: use access key, secret access key from env variable
dream11/odin pull request #86
Opened 2022-05-17 10:04 UTC by akshaypatidar1999

# Odin version(x.y.z)

## Features

## Resources

2022-05-17 12:17 UTC, brownhash requested changes
@akshaypatidar1999 @dhavalmehta07 @chouguleds Shouldn't we consider both approaches for input, environment variables and user input?

2022-05-17 12:18 UTC, brownhash requested changes
@akshaypatidar1999 plz bump the app version as well

2022-05-18 08:47 UTC, brownhash submitted a review, later dismissed

2022-05-20 09:50 UTC, BalkishanNanavath commented on internal/command/commands/configure.go
> +			config.BackendAddr = "http://odin-backend.dream11-stag.local:8000"
put this URL in constants

2022-05-20 09:51 UTC, BalkishanNanavath approved these changes

2022-05-24 07:41 UTC, surajgour-d11 approved these changes

2022-05-24 07:41 UTC, merged